image: php:8.2-fpm
pipelines:
    branches:
      feature/*:
            - step:
                  name: Docker Build
                  script:
                      - docker version
                      - export DOCKER_BUILDKIT=1
                      - docker build -t $AWS_ECR_REPOSITORY .
                      - docker save --output tmp-image.docker $AWS_ECR_REPOSITORY
                  services:
                    - docker
                  artifacts:
                    - tmp-image.docker
            - step:
                  name: Deploy to ECR
                  deployment: staging-qa
                  script:
                      - docker load --input ./tmp-image.docker
                      - docker images
                     # - docker tag lureg-qa $IMAGE_NAME
                      - pipe: atlassian/aws-ecr-push-image:2.4.0
                        variables:
                            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                            AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                            IMAGE_NAME: $AWS_ECR_REPOSITORY
                      - pipe: atlassian/ssh-run:0.8.1
                        variables:
                          SSH_USER: $SSH_USER
                          SERVER: $SSH_SERVER
                          SSH_KEY: $SSH_KEY
                          MODE: 'command'
                          COMMAND: 'cd /opt/webapps/lureg && sudo docker service update --force qa_lureg --image $AWS_ECR_REPOSITORY'

