version: '3.8'

services:
    app:
        restart: on-failure
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        environment:
            - APP_NAME=LUREG
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:4i+UCrVlNwRzqZZ5hw6dswsgW/PLv+o4QG/HhvRWJFo=
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - REDIS_HOST=redis
            - REDIS_CLIENT=predis
            - FILESYSTEM_DISK=local  # local, s3, public
        command: bash -c "composer install  && php artisan migrate  && php-fpm"

    db:
        image: mysql:8
        container_name: laravel_db
        ports:
            - "3358:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=lara
            - MYSQL_PASSWORD=root
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8097:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - db
            - app
            - redis

    redis:
        image: redis:alpine
        container_name: laravel_redis
        ports:
            - "6388:6379"

volumes:
    db_data:
networks:
    lara:
        driver: bridge
