version: '3.8'

services:
    app:
        restart: on-failure
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        environment:
            - APP_NAME=${APP_NAME}
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_KEY=${APP_KEY}
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=lureg
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - DB_CONNECTION=mysql
            - REDIS_HOST=redis
            - REDIS_CLIENT=${REDIS_CLIENT}
            - FILESYSTEM_DISK=local  # local, s3, public
            - PASSPORT_PASSWORD_CLIENT_ID=${PASSPORT_PASSWORD_CLIENT_ID}  #testing purposes only
            - PASSPORT_PASSWORD_CLIENT_SECRET=${PASSPORT_PASSWORD_CLIENT_SECRET}   #testing purposes only
            - APP_HOST_URL=${APP_HOST_URL}
        command: bash -c "composer install   && php artisan migrate  && php-fpm"
        networks:
            - lara

    db:
        image: mysql:8
        restart: on-failure
        container_name: laravel_db
        ports:
            - "3358:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=lureg
            - MYSQL_USER=lara
            - MYSQL_PASSWORD=root
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/mysql/mysql_backup:/var/lib/mysql_backup
        networks:
            - lara

    nginx:
        image: nginx:latest
        restart: on-failure
        container_name: laravel_nginx
        ports:
            - "8097:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - lara

    redis:
        image: redis:alpine
        restart: on-failure
        container_name: laravel_redis
        ports:
            - "6388:6379"
        networks:
            - lara

volumes:
    db_data:
networks:
    lara:
        driver: bridge
